import { InventoryRepository as repo } from './inventory.repository';
import { StockService } from './inventory.service';
import type { SeedModule } from '../../seed/types';

const RESTAURANT_INGREDIENTS = [
  {
    name: 'Rice (Matta)',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 85,
    reorder: 50,
    reorderQty: 50,
    cost: 55,
  },
  {
    name: 'Chicken',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 12,
    reorder: 15,
    reorderQty: 25,
    cost: 210,
  },
  {
    name: 'Cooking Oil',
    category: 'food' as const,
    unit: 'L',
    initialStock: 28,
    reorder: 20,
    reorderQty: 15,
    cost: 140,
  },
  {
    name: 'Onion',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 22,
    reorder: 25,
    reorderQty: 20,
    cost: 38,
  },
  {
    name: 'Coconut',
    category: 'food' as const,
    unit: 'pc',
    initialStock: 60,
    reorder: 40,
    reorderQty: 50,
    cost: 32,
  },
  {
    name: 'Tomato',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 15,
    reorder: 10,
    reorderQty: 15,
    cost: 45,
  },
  {
    name: 'Potato',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 35,
    reorder: 20,
    reorderQty: 25,
    cost: 30,
  },
  {
    name: 'Ginger-Garlic Paste',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 5,
    reorder: 3,
    reorderQty: 5,
    cost: 120,
  },
  {
    name: 'Turmeric Powder',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 3,
    reorder: 2,
    reorderQty: 2,
    cost: 280,
  },
  {
    name: 'Chilli Powder',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 4,
    reorder: 2,
    reorderQty: 2,
    cost: 320,
  },
  {
    name: 'Coriander Powder',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 3,
    reorder: 2,
    reorderQty: 2,
    cost: 200,
  },
  {
    name: 'Garam Masala',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 2,
    reorder: 1,
    reorderQty: 2,
    cost: 400,
  },
  {
    name: 'Salt',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 15,
    reorder: 10,
    reorderQty: 10,
    cost: 18,
  },
  {
    name: 'Sugar',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 12,
    reorder: 10,
    reorderQty: 10,
    cost: 42,
  },
  {
    name: 'Eggs',
    category: 'food' as const,
    unit: 'pc',
    initialStock: 120,
    reorder: 60,
    reorderQty: 60,
    cost: 7,
  },
  {
    name: 'Curd',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 8,
    reorder: 5,
    reorderQty: 5,
    cost: 60,
  },
  {
    name: 'Green Chillies',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 2,
    reorder: 1,
    reorderQty: 2,
    cost: 80,
  },
  {
    name: 'Curry Leaves',
    category: 'food' as const,
    unit: 'pc',
    initialStock: 10,
    reorder: 5,
    reorderQty: 5,
    cost: 5,
  },
  {
    name: 'Mustard Seeds',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 1,
    reorder: 1,
    reorderQty: 1,
    cost: 160,
  },
  {
    name: 'Sambar Powder',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 3,
    reorder: 2,
    reorderQty: 2,
    cost: 180,
  },
  {
    name: 'Fish (Kingfish)',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 6,
    reorder: 5,
    reorderQty: 8,
    cost: 350,
  },
  {
    name: 'Mutton',
    category: 'food' as const,
    unit: 'kg',
    initialStock: 0,
    reorder: 5,
    reorderQty: 10,
    cost: 650,
  },
];

const SOFT_DRINKS = [
  {
    name: 'Pepsi 750ml',
    category: 'softdrink' as const,
    unit: 'btl',
    initialStock: 48,
    reorder: 24,
    reorderQty: 24,
    cost: 35,
  },
  {
    name: 'Soda 300ml',
    category: 'softdrink' as const,
    unit: 'btl',
    initialStock: 96,
    reorder: 48,
    reorderQty: 48,
    cost: 12,
  },
  {
    name: 'Mineral Water 1L',
    category: 'softdrink' as const,
    unit: 'btl',
    initialStock: 18,
    reorder: 36,
    reorderQty: 24,
    cost: 15,
  },
  {
    name: 'Coca-Cola 750ml',
    category: 'softdrink' as const,
    unit: 'btl',
    initialStock: 36,
    reorder: 24,
    reorderQty: 24,
    cost: 35,
  },
  {
    name: 'Sprite 750ml',
    category: 'softdrink' as const,
    unit: 'btl',
    initialStock: 24,
    reorder: 12,
    reorderQty: 24,
    cost: 35,
  },
  {
    name: 'Mountain Dew 750ml',
    category: 'softdrink' as const,
    unit: 'btl',
    initialStock: 18,
    reorder: 12,
    reorderQty: 12,
    cost: 35,
  },
  {
    name: 'Fresh Lime Juice',
    category: 'softdrink' as const,
    unit: 'L',
    initialStock: 4,
    reorder: 2,
    reorderQty: 4,
    cost: 60,
  },
  {
    name: 'Buttermilk Packets',
    category: 'softdrink' as const,
    unit: 'pc',
    initialStock: 30,
    reorder: 20,
    reorderQty: 20,
    cost: 10,
  },
  {
    name: 'Tender Coconut Water',
    category: 'softdrink' as const,
    unit: 'pc',
    initialStock: 0,
    reorder: 20,
    reorderQty: 25,
    cost: 25,
  },
];

const KITCHEN_SUPPLIES = [
  {
    name: 'LPG Cylinder 19kg',
    category: 'kitchen' as const,
    unit: 'cyl',
    initialStock: 3,
    reorder: 2,
    reorderQty: 2,
    cost: 1900,
  },
  {
    name: 'LPG Cylinder 5kg',
    category: 'kitchen' as const,
    unit: 'cyl',
    initialStock: 2,
    reorder: 1,
    reorderQty: 2,
    cost: 650,
  },
  {
    name: 'Disposable Gloves',
    category: 'kitchen' as const,
    unit: 'pack',
    initialStock: 10,
    reorder: 5,
    reorderQty: 10,
    cost: 85,
  },
  {
    name: 'Aluminium Foil',
    category: 'kitchen' as const,
    unit: 'roll',
    initialStock: 4,
    reorder: 2,
    reorderQty: 3,
    cost: 180,
  },
  {
    name: 'Cling Wrap',
    category: 'kitchen' as const,
    unit: 'roll',
    initialStock: 3,
    reorder: 2,
    reorderQty: 3,
    cost: 120,
  },
  {
    name: 'Kitchen Towels',
    category: 'kitchen' as const,
    unit: 'pack',
    initialStock: 6,
    reorder: 3,
    reorderQty: 6,
    cost: 95,
  },
  {
    name: 'Match Box',
    category: 'kitchen' as const,
    unit: 'box',
    initialStock: 20,
    reorder: 10,
    reorderQty: 20,
    cost: 2,
  },
  {
    name: 'Toothpicks',
    category: 'kitchen' as const,
    unit: 'pack',
    initialStock: 15,
    reorder: 5,
    reorderQty: 10,
    cost: 10,
  },
];

const CLEANING_MATERIALS = [
  {
    name: 'Phenyl 5L',
    category: 'consumables' as const,
    unit: 'can',
    initialStock: 6,
    reorder: 4,
    reorderQty: 4,
    cost: 260,
  },
  {
    name: 'Tissue Rolls',
    category: 'consumables' as const,
    unit: 'pc',
    initialStock: 40,
    reorder: 24,
    reorderQty: 24,
    cost: 22,
  },
  {
    name: 'Toilet Cleaner',
    category: 'consumables' as const,
    unit: 'btl',
    initialStock: 8,
    reorder: 4,
    reorderQty: 6,
    cost: 95,
  },
  {
    name: 'Harpic',
    category: 'consumables' as const,
    unit: 'btl',
    initialStock: 6,
    reorder: 4,
    reorderQty: 4,
    cost: 85,
  },
  {
    name: 'Lizol Floor Cleaner',
    category: 'consumables' as const,
    unit: 'btl',
    initialStock: 5,
    reorder: 3,
    reorderQty: 4,
    cost: 120,
  },
  {
    name: 'Bleach Liquid',
    category: 'consumables' as const,
    unit: 'L',
    initialStock: 4,
    reorder: 2,
    reorderQty: 4,
    cost: 60,
  },
  {
    name: 'Glass Cleaner',
    category: 'consumables' as const,
    unit: 'btl',
    initialStock: 3,
    reorder: 2,
    reorderQty: 3,
    cost: 140,
  },
  {
    name: 'Dishwash Liquid',
    category: 'consumables' as const,
    unit: 'L',
    initialStock: 8,
    reorder: 5,
    reorderQty: 5,
    cost: 110,
  },
  {
    name: 'Scrub Pads',
    category: 'consumables' as const,
    unit: 'pack',
    initialStock: 10,
    reorder: 5,
    reorderQty: 10,
    cost: 25,
  },
  {
    name: 'Garbage Bags (Large)',
    category: 'consumables' as const,
    unit: 'pack',
    initialStock: 15,
    reorder: 10,
    reorderQty: 10,
    cost: 45,
  },
  {
    name: 'Garbage Bags (Small)',
    category: 'consumables' as const,
    unit: 'pack',
    initialStock: 20,
    reorder: 10,
    reorderQty: 10,
    cost: 30,
  },
  {
    name: 'Mop Heads',
    category: 'consumables' as const,
    unit: 'pc',
    initialStock: 6,
    reorder: 3,
    reorderQty: 6,
    cost: 65,
  },
  {
    name: 'Brooms',
    category: 'consumables' as const,
    unit: 'pc',
    initialStock: 4,
    reorder: 2,
    reorderQty: 3,
    cost: 45,
  },
];

const ROOM_AMENITIES = [
  {
    name: 'Bath Towels',
    category: 'amenities' as const,
    unit: 'pc',
    initialStock: 34,
    reorder: 20,
    reorderQty: 20,
    cost: 180,
  },
  {
    name: 'Bedsheets',
    category: 'amenities' as const,
    unit: 'set',
    initialStock: 26,
    reorder: 15,
    reorderQty: 15,
    cost: 420,
  },
  {
    name: 'Pillow Covers',
    category: 'amenities' as const,
    unit: 'pc',
    initialStock: 40,
    reorder: 20,
    reorderQty: 20,
    cost: 60,
  },
  {
    name: 'Toilet Soap',
    category: 'amenities' as const,
    unit: 'pc',
    initialStock: 14,
    reorder: 30,
    reorderQty: 60,
    cost: 8,
  },
  {
    name: 'Shampoo Sachets',
    category: 'amenities' as const,
    unit: 'pc',
    initialStock: 60,
    reorder: 50,
    reorderQty: 100,
    cost: 4,
  },
  {
    name: 'Hand Wash',
    category: 'amenities' as const,
    unit: 'btl',
    initialStock: 6,
    reorder: 4,
    reorderQty: 6,
    cost: 95,
  },
  {
    name: 'Mosquito Repellent',
    category: 'amenities' as const,
    unit: 'pc',
    initialStock: 8,
    reorder: 5,
    reorderQty: 10,
    cost: 55,
  },
  {
    name: 'Room Freshener',
    category: 'amenities' as const,
    unit: 'pc',
    initialStock: 5,
    reorder: 3,
    reorderQty: 5,
    cost: 120,
  },
  {
    name: 'Tea Bags',
    category: 'amenities' as const,
    unit: 'pack',
    initialStock: 12,
    reorder: 6,
    reorderQty: 12,
    cost: 25,
  },
  {
    name: 'Coffee Sachets',
    category: 'amenities' as const,
    unit: 'pack',
    initialStock: 10,
    reorder: 5,
    reorderQty: 10,
    cost: 15,
  },
  {
    name: 'Drinking Glasses',
    category: 'amenities' as const,
    unit: 'pc',
    initialStock: 24,
    reorder: 12,
    reorderQty: 12,
    cost: 35,
  },
];

const PACKAGING = [
  {
    name: 'Parcel Boxes (Meals)',
    category: 'packaging' as const,
    unit: 'pc',
    initialStock: 100,
    reorder: 50,
    reorderQty: 100,
    cost: 8,
  },
  {
    name: 'Parcel Boxes (Biriyani)',
    category: 'packaging' as const,
    unit: 'pc',
    initialStock: 60,
    reorder: 30,
    reorderQty: 60,
    cost: 12,
  },
  {
    name: 'Paper Bags (Small)',
    category: 'packaging' as const,
    unit: 'pc',
    initialStock: 200,
    reorder: 100,
    reorderQty: 200,
    cost: 3,
  },
  {
    name: 'Paper Bags (Large)',
    category: 'packaging' as const,
    unit: 'pc',
    initialStock: 100,
    reorder: 50,
    reorderQty: 100,
    cost: 5,
  },
  {
    name: 'Plastic Spoons',
    category: 'packaging' as const,
    unit: 'pack',
    initialStock: 20,
    reorder: 10,
    reorderQty: 20,
    cost: 25,
  },
  {
    name: 'Thermocol Bowls',
    category: 'packaging' as const,
    unit: 'pc',
    initialStock: 50,
    reorder: 25,
    reorderQty: 50,
    cost: 6,
  },
  {
    name: 'Straws',
    category: 'packaging' as const,
    unit: 'pack',
    initialStock: 10,
    reorder: 5,
    reorderQty: 10,
    cost: 15,
  },
  {
    name: 'Carry Bags (Plastic)',
    category: 'packaging' as const,
    unit: 'pack',
    initialStock: 15,
    reorder: 10,
    reorderQty: 10,
    cost: 35,
  },
];

const ALL_ITEMS = [
  ...RESTAURANT_INGREDIENTS,
  ...SOFT_DRINKS,
  ...KITCHEN_SUPPLIES,
  ...CLEANING_MATERIALS,
  ...ROOM_AMENITIES,
  ...PACKAGING,
];

export const inventorySeed: SeedModule = {
  name: 'inventory',
  dependsOn: [],

  async run(): Promise<void> {
    const count = await repo.count();
    if (count > 0) {
      console.log('[seed] Inventory already seeded, skipping.');
      return;
    }

    console.log(`[seed] Seeding ${ALL_ITEMS.length} inventory items...`);

    for (const item of ALL_ITEMS) {
      try {
        await StockService.createItemWithOpeningStock({
          name: item.name,
          category: item.category,
          unit: item.unit,
          initialStock: item.initialStock,
          reorder: item.reorder,
          reorderQty: item.reorderQty,
          cost: item.cost,
          minStock: Math.round(item.reorder * 0.5),
          maxStock: item.reorder * 3,
        });
      } catch (err: any) {
        if (err.message?.includes('already exists')) continue;
        throw err;
      }
    }

    console.log(
      `[seed] Seeded ${ALL_ITEMS.length} inventory items with realistic stock levels.`,
    );
  },

  async verify(): Promise<boolean> {
    const count = await repo.count();
    return count >= ALL_ITEMS.length;
  },
};
