import type { SeedModule } from '../../seed/types';
import { AnalyticsRepository } from './analytics.repository';
import type * as T from './analytics.types';

type KpiSeed = Omit<T.KpiDefinition, 'id'>;

const CATEGORIES = {
  revenue: 'revenue' as T.KpiCategory,
  occupancy: 'occupancy' as T.KpiCategory,
  restaurant: 'restaurant' as T.KpiCategory,
  bar: 'bar' as T.KpiCategory,
  inventory: 'inventory' as T.KpiCategory,
  purchasing: 'purchasing' as T.KpiCategory,
  finance: 'finance' as T.KpiCategory,
  gst: 'gst' as T.KpiCategory,
  hotel: 'hotel' as T.KpiCategory,
  employee: 'employee' as T.KpiCategory,
};

const KPI_DEFINITIONS: KpiSeed[] = [
  // ── Revenue (3) ─────────────────────────────────────────────────────
  {
    key: 'daily_revenue',
    name: 'Daily Revenue',
    description:
      'Total posted revenue for the current day across all departments',
    category: CATEGORIES.revenue,
    unit: 'INR',
    formula: 'SUM(journal_entries.credit_total) WHERE status=posted',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'department_revenue',
    name: 'Department Revenue',
    description: 'Revenue split by voucher type per department',
    category: CATEGORIES.revenue,
    unit: 'INR',
    formula: 'Revenue split by voucher_type',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'monthly_revenue',
    name: 'Monthly Revenue',
    description: 'Aggregate revenue for the current month from daily summaries',
    category: CATEGORIES.revenue,
    unit: 'INR',
    formula: 'SUM(daily_summaries.total_revenue)',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },

  // ── Occupancy (3) ──────────────────────────────────────────────────
  {
    key: 'occupancy_rate',
    name: 'Occupancy Rate',
    description: 'Percentage of occupied rooms out of total available rooms',
    category: CATEGORIES.occupancy,
    unit: '%',
    formula: '(occupied_rooms / total_rooms) * 100',
    decimalPlaces: 1,
    isPercentage: true,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'hotel'],
  },
  {
    key: 'adr',
    name: 'Average Daily Rate',
    description: 'Average revenue earned per occupied room per night',
    category: CATEGORIES.occupancy,
    unit: 'INR',
    formula: 'room_revenue / occupied_room_nights',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'hotel'],
  },
  {
    key: 'revpar',
    name: 'Revenue Per Available Room',
    description: 'Revenue generated per available room regardless of occupancy',
    category: CATEGORIES.occupancy,
    unit: 'INR',
    formula: 'room_revenue / available_room_nights',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'hotel'],
  },

  // ── Restaurant (3) ─────────────────────────────────────────────────
  {
    key: 'restaurant_covers',
    name: 'Restaurant Covers',
    description: 'Total number of guests served in the restaurant today',
    category: CATEGORIES.restaurant,
    unit: 'count',
    formula: 'COUNT(restaurant_orders) WHERE date=today',
    decimalPlaces: 0,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'restaurant'],
  },
  {
    key: 'average_bill',
    name: 'Average Bill',
    description: 'Average revenue per guest cover in the restaurant',
    category: CATEGORIES.restaurant,
    unit: 'INR',
    formula: 'total_revenue / total_covers',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'restaurant'],
  },
  {
    key: 'table_turnover',
    name: 'Table Turnover',
    description:
      'Number of times tables are seated and cleared in a service period',
    category: CATEGORIES.restaurant,
    unit: 'turns',
    formula: 'total_covers / total_tables',
    decimalPlaces: 1,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'restaurant'],
  },

  // ── Bar (3) ────────────────────────────────────────────────────────
  {
    key: 'bar_sales',
    name: 'Bar Sales',
    description: 'Total sales revenue from bar operations',
    category: CATEGORIES.bar,
    unit: 'INR',
    formula: 'SUM(bar_sales.total)',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'bar'],
  },
  {
    key: 'bartender_productivity',
    name: 'Bartender Productivity',
    description: 'Number of beverage pours prepared by each bartender',
    category: CATEGORIES.bar,
    unit: 'pours',
    formula: 'COUNT(pour_log) GROUP BY bartender',
    decimalPlaces: 0,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 600,
    roles: ['owner', 'manager', 'bar'],
  },
  {
    key: 'popular_brands',
    name: 'Popular Brands',
    description: 'Most frequently sold beverage brands by transaction count',
    category: CATEGORIES.bar,
    unit: 'count',
    formula: 'COUNT(bar_sale_lines) GROUP BY brand',
    decimalPlaces: 0,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['bar', 'manager'],
  },

  // ── Inventory (5) ──────────────────────────────────────────────────
  {
    key: 'inventory_turnover',
    name: 'Inventory Turnover',
    description: 'Rate at which inventory is sold and replaced over a period',
    category: CATEGORIES.inventory,
    unit: 'turns',
    formula: 'COGS / avg_inventory_value',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'inventory'],
  },
  {
    key: 'inventory_value',
    name: 'Inventory Value',
    description: 'Total monetary value of all inventory items on hand',
    category: CATEGORIES.inventory,
    unit: 'INR',
    formula: 'SUM(quantity * unit_cost)',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'inventory'],
  },
  {
    key: 'shrinkage_percent',
    name: 'Shrinkage %',
    description:
      'Percentage of inventory value lost due to theft, damage, or error',
    category: CATEGORIES.inventory,
    unit: '%',
    formula: '(shrinkage_value / total_value) * 100',
    decimalPlaces: 2,
    isPercentage: true,
    higherIsBetter: false,
    minRefreshInterval: 3600,
    roles: ['inventory', 'manager'],
  },
  {
    key: 'dead_stock_count',
    name: 'Dead Stock Items',
    description: 'Items with no sales or movement in the last 90 days',
    category: CATEGORIES.inventory,
    unit: 'count',
    formula: 'COUNT(items WHERE no_movement > 90 days)',
    decimalPlaces: 0,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 86400,
    roles: ['inventory', 'manager'],
  },
  {
    key: 'reorder_alerts',
    name: 'Reorder Alerts',
    description: 'Count of items whose stock has fallen below reorder level',
    category: CATEGORIES.inventory,
    unit: 'count',
    formula: 'COUNT(items WHERE stock <= reorder_level)',
    decimalPlaces: 0,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 300,
    roles: ['inventory', 'manager'],
  },

  // ── Purchasing (3) ─────────────────────────────────────────────────
  {
    key: 'purchase_efficiency',
    name: 'Purchase Efficiency',
    description: 'Percentage of purchase orders delivered on time',
    category: CATEGORIES.purchasing,
    unit: '%',
    formula: '(on_time_deliveries / total_orders) * 100',
    decimalPlaces: 1,
    isPercentage: true,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'purchasing'],
  },
  {
    key: 'supplier_on_time_rate',
    name: 'Supplier On-Time Rate',
    description: 'Average on-time delivery rate across all suppliers',
    category: CATEGORIES.purchasing,
    unit: '%',
    formula: 'AVG(supplier.on_time_rate)',
    decimalPlaces: 1,
    isPercentage: true,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['purchasing', 'manager'],
  },
  {
    key: 'supplier_quality_rating',
    name: 'Supplier Quality Rating',
    description: 'Average quality rating received from suppliers',
    category: CATEGORIES.purchasing,
    unit: 'rating',
    formula: 'AVG(supplier.quality_rating)',
    decimalPlaces: 1,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['purchasing', 'manager'],
  },

  // ── Finance (7) ────────────────────────────────────────────────────
  {
    key: 'gross_profit',
    name: 'Gross Profit',
    description: 'Revenue minus cost of goods sold',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'total_revenue - cogs',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'gross_margin',
    name: 'Gross Margin',
    description: 'Gross profit as a percentage of total revenue',
    category: CATEGORIES.finance,
    unit: '%',
    formula: '(gross_profit / total_revenue) * 100',
    decimalPlaces: 1,
    isPercentage: true,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'net_profit',
    name: 'Net Profit',
    description: 'Gross profit minus all operating and administrative expenses',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'total_revenue - total_expenses',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'net_margin',
    name: 'Net Margin',
    description: 'Net profit as a percentage of total revenue',
    category: CATEGORIES.finance,
    unit: '%',
    formula: '(net_profit / total_revenue) * 100',
    decimalPlaces: 1,
    isPercentage: true,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'cash_flow',
    name: 'Cash Flow',
    description: 'Net cash generated or consumed during the period',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'cash_in - cash_out',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'cash_position',
    name: 'Cash Position',
    description: 'Total cash balance across all cash accounts',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'SUM(balance) WHERE account_type=cash',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'bank_position',
    name: 'Bank Position',
    description: 'Total balance across all bank accounts',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'SUM(balance) WHERE account_type=bank',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },

  // ── GST (3) ────────────────────────────────────────────────────────
  {
    key: 'gst_payable',
    name: 'GST Payable',
    description: 'Total output GST collected on sales and services',
    category: CATEGORIES.gst,
    unit: 'INR',
    formula: 'SUM(gst_amount) WHERE gst_type=output',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 3600,
    roles: ['owner', 'accountant', 'finance'],
  },
  {
    key: 'gst_input_credit',
    name: 'GST Input Credit',
    description: 'Total input GST available for credit on purchases',
    category: CATEGORIES.gst,
    unit: 'INR',
    formula: 'SUM(gst_amount) WHERE gst_type=input',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'accountant', 'finance'],
  },
  {
    key: 'gst_liability',
    name: 'GST Net Liability',
    description: 'Net GST liability payable to tax authorities',
    category: CATEGORIES.gst,
    unit: 'INR',
    formula: 'gst_payable - gst_input_credit',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 3600,
    roles: ['owner', 'accountant', 'finance'],
  },

  // ── Receivables & Payables (3) ─────────────────────────────────────
  {
    key: 'receivables',
    name: 'Accounts Receivable',
    description:
      'Total amounts owed by customers for goods and services provided',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'SUM(balance) WHERE account_type=receivable',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'payables',
    name: 'Accounts Payable',
    description:
      'Total amounts owed to suppliers for goods and services received',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'SUM(balance) WHERE account_type=payable',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },
  {
    key: 'outstanding_payments',
    name: 'Outstanding Payments',
    description: 'Sum of total receivables and payables outstanding',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'receivables + payables',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },

  // ── Department Profitability (3) ───────────────────────────────────
  {
    key: 'dept_room_profit',
    name: 'Room Dept Profit',
    description: 'Net profit from room operations after direct expenses',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'room_revenue - room_expenses',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'finance'],
  },
  {
    key: 'dept_restaurant_profit',
    name: 'Restaurant Dept Profit',
    description: 'Net profit from restaurant operations after direct expenses',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'restaurant_revenue - restaurant_expenses',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'finance'],
  },
  {
    key: 'dept_bar_profit',
    name: 'Bar Dept Profit',
    description: 'Net profit from bar operations after direct expenses',
    category: CATEGORIES.finance,
    unit: 'INR',
    formula: 'bar_revenue - bar_expenses',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'finance'],
  },

  // ── Waste & Loss (4) ───────────────────────────────────────────────
  {
    key: 'waste_percent',
    name: 'Waste %',
    description: 'Percentage of inventory value written off as waste',
    category: CATEGORIES.inventory,
    unit: '%',
    formula: '(waste_value / total_consumption) * 100',
    decimalPlaces: 2,
    isPercentage: true,
    higherIsBetter: false,
    minRefreshInterval: 86400,
    roles: ['owner', 'manager', 'inventory'],
  },
  {
    key: 'complimentary_percent',
    name: 'Complimentary %',
    description:
      'Value of complimentary items as a percentage of total revenue',
    category: CATEGORIES.restaurant,
    unit: '%',
    formula: '(complimentary_value / total_revenue) * 100',
    decimalPlaces: 2,
    isPercentage: true,
    higherIsBetter: false,
    minRefreshInterval: 86400,
    roles: ['owner', 'manager', 'restaurant'],
  },
  {
    key: 'cancellation_rate',
    name: 'Cancellation %',
    description: 'Percentage of bookings that were cancelled',
    category: CATEGORIES.hotel,
    unit: '%',
    formula: '(cancelled_bookings / total_bookings) * 100',
    decimalPlaces: 2,
    isPercentage: true,
    higherIsBetter: false,
    minRefreshInterval: 3600,
    roles: ['owner', 'manager', 'hotel'],
  },
  {
    key: 'refund_percent',
    name: 'Refund %',
    description: 'Total refunds issued as a percentage of revenue',
    category: CATEGORIES.finance,
    unit: '%',
    formula: '(refund_amount / total_revenue) * 100',
    decimalPlaces: 2,
    isPercentage: true,
    higherIsBetter: false,
    minRefreshInterval: 86400,
    roles: ['owner', 'manager', 'accountant', 'finance'],
  },

  // ── Seasonality & Trends (2) ───────────────────────────────────────
  {
    key: 'peak_hour_revenue',
    name: 'Peak Hour Revenue',
    description: 'Highest revenue-generating hour in the current period',
    category: CATEGORIES.revenue,
    unit: 'INR',
    formula: 'MAX(revenue BY hour)',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: true,
    minRefreshInterval: 300,
    roles: ['owner', 'manager', 'restaurant', 'bar'],
  },
  {
    key: 'seasonality_index',
    name: 'Seasonality Index',
    description: 'Ratio of current month revenue to average monthly revenue',
    category: CATEGORIES.revenue,
    unit: 'ratio',
    formula: 'month_revenue / avg_monthly_revenue',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 86400,
    roles: ['owner', 'manager'],
  },

  // ── Employee (3) ───────────────────────────────────────────────────
  {
    key: 'payroll_cost',
    name: 'Payroll Cost',
    description: 'Total cost of salaries, wages, and benefits',
    category: CATEGORIES.employee,
    unit: 'INR',
    formula: 'SUM(salary + wages)',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 86400,
    roles: ['owner', 'manager', 'finance'],
  },
  {
    key: 'employee_count',
    name: 'Employee Count',
    description: 'Total number of active employees on payroll',
    category: CATEGORIES.employee,
    unit: 'count',
    formula: 'COUNT(active_employees)',
    decimalPlaces: 0,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 86400,
    roles: ['owner', 'manager'],
  },
  {
    key: 'cost_per_employee',
    name: 'Cost Per Employee',
    description: 'Average payroll cost per active employee',
    category: CATEGORIES.employee,
    unit: 'INR',
    formula: 'payroll_cost / employee_count',
    decimalPlaces: 2,
    isPercentage: false,
    higherIsBetter: false,
    minRefreshInterval: 86400,
    roles: ['owner', 'finance'],
  },
];

type DashboardSeed = Omit<T.DashboardConfig, 'id'>;

const DASHBOARD_CONFIGS: DashboardSeed[] = [
  // ── Owner Dashboard ─────────────────────────────────────────────────
  {
    role: 'owner',
    name: 'Owner Dashboard',
    description:
      'Executive overview of the entire business with revenue, operations, and financial health',
    refreshInterval: 300,
    sections: [
      {
        id: 'owner-summary',
        title: 'Executive Summary',
        type: 'kpi_grid',
        kpiKeys: [
          'daily_revenue',
          'monthly_revenue',
          'gross_profit',
          'net_profit',
          'occupancy_rate',
          'gst_liability',
        ],
        size: 'large',
        order: 1,
      },
      {
        id: 'owner-revenue',
        title: 'Revenue Breakdown',
        type: 'chart',
        kpiKeys: ['department_revenue', 'monthly_revenue', 'daily_revenue'],
        chartType: 'pie',
        size: 'medium',
        order: 2,
      },
      {
        id: 'owner-operations',
        title: 'Operational KPIs',
        type: 'kpi_grid',
        kpiKeys: [
          'inventory_turnover',
          'purchase_efficiency',
          'restaurant_covers',
          'bar_sales',
          'adr',
          'revpar',
          'cash_flow',
          'employee_count',
        ],
        size: 'large',
        order: 3,
      },
      {
        id: 'owner-financial',
        title: 'Financial Health',
        type: 'kpi_grid',
        kpiKeys: [
          'cash_position',
          'bank_position',
          'receivables',
          'payables',
          'gst_payable',
          'gst_input_credit',
        ],
        size: 'medium',
        order: 4,
      },
    ],
  },
  // ── Manager Dashboard ───────────────────────────────────────────────
  {
    role: 'manager',
    name: 'Manager Dashboard',
    description: 'Daily operational overview for general management',
    refreshInterval: 300,
    sections: [
      {
        id: 'mgr-daily',
        title: 'Daily Operations',
        type: 'kpi_grid',
        kpiKeys: [
          'daily_revenue',
          'restaurant_covers',
          'bar_sales',
          'occupancy_rate',
        ],
        size: 'medium',
        order: 1,
      },
      {
        id: 'mgr-dept-revenue',
        title: 'Department Revenue',
        type: 'chart',
        kpiKeys: ['department_revenue'],
        chartType: 'bar',
        size: 'medium',
        order: 2,
      },
      {
        id: 'mgr-occupancy-sales',
        title: 'Occupancy & Sales',
        type: 'kpi_grid',
        kpiKeys: ['adr', 'revpar', 'average_bill', 'table_turnover'],
        size: 'medium',
        order: 3,
      },
      {
        id: 'mgr-alerts',
        title: 'Alerts',
        type: 'table',
        kpiKeys: ['reorder_alerts', 'outstanding_payments', 'waste_percent'],
        size: 'large',
        order: 4,
      },
    ],
  },
  // ── Accountant Dashboard ────────────────────────────────────────────
  {
    role: 'accountant',
    name: 'Accountant Dashboard',
    description: 'Financial and tax summary for the accounting team',
    refreshInterval: 600,
    sections: [
      {
        id: 'acct-financial',
        title: 'Financial Summary',
        type: 'kpi_grid',
        kpiKeys: [
          'gross_profit',
          'gross_margin',
          'net_profit',
          'net_margin',
          'receivables',
          'payables',
        ],
        size: 'large',
        order: 1,
      },
      {
        id: 'acct-gst',
        title: 'GST Summary',
        type: 'kpi_grid',
        kpiKeys: [
          'gst_payable',
          'gst_input_credit',
          'gst_liability',
          'cash_flow',
        ],
        size: 'medium',
        order: 2,
      },
      {
        id: 'acct-receivables',
        title: 'Receivables / Payables',
        type: 'table',
        kpiKeys: ['receivables', 'payables', 'outstanding_payments'],
        size: 'large',
        order: 3,
      },
    ],
  },
  // ── Restaurant Dashboard ────────────────────────────────────────────
  {
    role: 'restaurant',
    name: 'Restaurant Dashboard',
    description:
      'Restaurant service metrics, popular items, and kitchen performance',
    refreshInterval: 300,
    sections: [
      {
        id: 'rest-today',
        title: "Today's Service",
        type: 'kpi_grid',
        kpiKeys: [
          'restaurant_covers',
          'average_bill',
          'table_turnover',
          'complimentary_percent',
        ],
        size: 'medium',
        order: 1,
      },
      {
        id: 'rest-popular',
        title: 'Popular Items',
        type: 'table',
        kpiKeys: ['restaurant_covers'],
        size: 'medium',
        order: 2,
      },
      {
        id: 'rest-kitchen',
        title: 'Kitchen Performance',
        type: 'chart',
        kpiKeys: ['restaurant_covers', 'peak_hour_revenue'],
        chartType: 'bar',
        size: 'medium',
        order: 3,
      },
    ],
  },
  // ── Bar Dashboard ───────────────────────────────────────────────────
  {
    role: 'bar',
    name: 'Bar Dashboard',
    description: 'Bar sales, popular brands, and bartender productivity',
    refreshInterval: 300,
    sections: [
      {
        id: 'bar-sales',
        title: 'Bar Sales',
        type: 'kpi_grid',
        kpiKeys: [
          'bar_sales',
          'popular_brands',
          'bartender_productivity',
          'peak_hour_revenue',
        ],
        size: 'medium',
        order: 1,
      },
      {
        id: 'bar-brands',
        title: 'Popular Brands',
        type: 'table',
        kpiKeys: ['popular_brands'],
        size: 'medium',
        order: 2,
      },
      {
        id: 'bar-bartenders',
        title: 'Bartender Performance',
        type: 'chart',
        kpiKeys: ['bartender_productivity'],
        chartType: 'bar',
        size: 'medium',
        order: 3,
      },
    ],
  },
  // ── Hotel Dashboard ─────────────────────────────────────────────────
  {
    role: 'hotel',
    name: 'Hotel Dashboard',
    description:
      'Room occupancy, booking source analysis, and seasonality trends',
    refreshInterval: 600,
    sections: [
      {
        id: 'hotel-occupancy',
        title: 'Occupancy',
        type: 'kpi_grid',
        kpiKeys: ['occupancy_rate', 'adr', 'revpar', 'cancellation_rate'],
        size: 'medium',
        order: 1,
      },
      {
        id: 'hotel-bookings',
        title: 'Booking Sources',
        type: 'chart',
        kpiKeys: ['occupancy_rate', 'cancellation_rate'],
        chartType: 'pie',
        size: 'medium',
        order: 2,
      },
      {
        id: 'hotel-seasonality',
        title: 'Seasonality',
        type: 'chart',
        kpiKeys: ['seasonality_index', 'monthly_revenue'],
        chartType: 'line',
        size: 'large',
        order: 3,
      },
    ],
  },
  // ── Inventory Dashboard ─────────────────────────────────────────────
  {
    role: 'inventory',
    name: 'Inventory Dashboard',
    description: 'Stock status, reorder alerts, and fast / slow moving items',
    refreshInterval: 600,
    sections: [
      {
        id: 'inv-stock',
        title: 'Stock Status',
        type: 'kpi_grid',
        kpiKeys: [
          'inventory_value',
          'inventory_turnover',
          'shrinkage_percent',
          'dead_stock_count',
        ],
        size: 'medium',
        order: 1,
      },
      {
        id: 'inv-reorder',
        title: 'Reorder Alerts',
        type: 'table',
        kpiKeys: ['reorder_alerts'],
        size: 'medium',
        order: 2,
      },
      {
        id: 'inv-movers',
        title: 'Fast / Slow Movers',
        type: 'table',
        kpiKeys: ['inventory_turnover', 'dead_stock_count'],
        size: 'large',
        order: 3,
      },
    ],
  },
  // ── Purchasing Dashboard ────────────────────────────────────────────
  {
    role: 'purchasing',
    name: 'Purchasing Dashboard',
    description: 'Supplier performance tracking and procurement efficiency',
    refreshInterval: 3600,
    sections: [
      {
        id: 'purch-supplier',
        title: 'Supplier Performance',
        type: 'kpi_grid',
        kpiKeys: [
          'purchase_efficiency',
          'supplier_on_time_rate',
          'supplier_quality_rating',
          'inventory_turnover',
        ],
        size: 'medium',
        order: 1,
      },
      {
        id: 'purch-efficiency',
        title: 'Efficiency Metrics',
        type: 'table',
        kpiKeys: ['purchase_efficiency', 'supplier_on_time_rate'],
        size: 'medium',
        order: 2,
      },
    ],
  },
  // ── Finance Dashboard ───────────────────────────────────────────────
  {
    role: 'finance',
    name: 'Finance Dashboard',
    description: 'Profitability, cash position, and departmental P&L',
    refreshInterval: 600,
    sections: [
      {
        id: 'fin-profitability',
        title: 'Profitability',
        type: 'kpi_grid',
        kpiKeys: [
          'gross_profit',
          'gross_margin',
          'net_profit',
          'net_margin',
          'dept_room_profit',
          'dept_restaurant_profit',
        ],
        size: 'large',
        order: 1,
      },
      {
        id: 'fin-cash',
        title: 'Cash Position',
        type: 'kpi_grid',
        kpiKeys: [
          'cash_position',
          'bank_position',
          'cash_flow',
          'outstanding_payments',
        ],
        size: 'medium',
        order: 2,
      },
      {
        id: 'fin-dept-pl',
        title: 'Department P&L',
        type: 'table',
        kpiKeys: [
          'dept_room_profit',
          'dept_restaurant_profit',
          'dept_bar_profit',
        ],
        size: 'large',
        order: 3,
      },
    ],
  },
];

export const analyticsSeed: SeedModule = {
  name: 'analytics',
  dependsOn: ['auth', 'accounting'],

  async run(): Promise<void> {
    try {
      const existing = await AnalyticsRepository.getKpiCount();
      if (existing > 0) {
        console.log(
          '[analytics.seed] KPI definitions already exist, skipping...',
        );
        return;
      }

      console.log('[analytics.seed] Seeding analytics domain...');

      let kpiCount = 0;
      for (const def of KPI_DEFINITIONS) {
        await AnalyticsRepository.createKpiDefinition(def);
        kpiCount++;
      }
      console.log(`[analytics.seed]   Created ${kpiCount} KPI definitions`);

      let dashCount = 0;
      for (const config of DASHBOARD_CONFIGS) {
        await AnalyticsRepository.createDashboardConfig(config);
        dashCount++;
      }
      console.log(`[analytics.seed]   Created ${dashCount} dashboard configs`);

      console.log('[analytics.seed] Analytics seeding complete.');
    } catch (err) {
      console.error('[analytics.seed] Seeding failed:', err);
    }
  },

  async verify(): Promise<boolean> {
    const count = await AnalyticsRepository.getKpiCount();
    return count >= KPI_DEFINITIONS.length;
  },
};
