apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  namespace: deepa-bms
  labels:
    app.kubernetes.io/part-of: deepa-bms
    app.kubernetes.io/component: sqlite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
