#!/data/data/com.termux/files/usr/bin/env bash
# =============================================================================
# slo-config.sh — Generate Prometheus recording rules & burn-rate alerts for the
# DeepaBMS Service Level Objectives (SLOs).
#
# Produces: docker/prometheus/alerts/slo.rules.yml
#   • API Availability   — 99.9% successful (non-5xx) requests
#   • API Latency       — 99% of requests under 1s
#   • Database Uptime   — 99.99% of probes successful
#   • Backup Freshness  — at least one successful backup every 24h
# Also generates multi-window burn-rate alerts per Google SRE guidance.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
OUT_DIR="$PROJECT_DIR/docker/prometheus/alerts"
OUT_FILE="$OUT_DIR/slo.rules.yml"

mkdir -p "$OUT_DIR"

cat > "$OUT_FILE" <<'YAML'
# =============================================================================
# DeepaBMS — SLO Recording Rules & Burn-Rate Alerts (generated by slo-config.sh)
# =============================================================================
groups:
  # --------------------------------------------------------------------------
  # API Availability 99.9%  (successful = non-5xx responses)
  # --------------------------------------------------------------------------
  - name: slo-api-availability
    rules:
      - record: slo:api_availability:ratio_rate5m
        expr: |
          sum(rate(http_requests_total{service="backend",status!~"5.."}[5m]))
            / sum(rate(http_requests_total{service="backend"}[5m]))
      - record: slo:api_availability:ratio_rate30m
        expr: |
          sum(rate(http_requests_total{service="backend",status!~"5.."}[30m]))
            / sum(rate(http_requests_total{service="backend"}[30m]))
      - record: slo:api_availability:error_burn_rate_1h
        expr: |
          (1 - 0.999) * (1 - slo:api_availability:ratio_rate5m)
      - record: slo:api_availability:error_burn_rate_6h
        expr: |
          (1 - 0.999) * (1 - slo:api_availability:ratio_rate30m)

  # --------------------------------------------------------------------------
  # API Latency 99% of requests < 1s
  # --------------------------------------------------------------------------
  - name: slo-api-latency
    rules:
      - record: slo:api_latency:ratio_rate5m
        expr: |
          1 - (sum(rate(http_request_duration_seconds_count{service="backend",le="1"}[5m]))
            / sum(rate(http_request_duration_seconds_count{service="backend"}[5m])))
      - record: slo:api_latency:ratio_rate30m
        expr: |
          1 - (sum(rate(http_request_duration_seconds_count{service="backend",le="1"}[30m]))
            / sum(rate(http_request_duration_seconds_count{service="backend"}[30m])))
      - record: slo:api_latency:error_burn_rate_1h
        expr: |
          (1 - 0.99) * slo:api_latency:ratio_rate5m
      - record: slo:api_latency:error_burn_rate_6h
        expr: |
          (1 - 0.99) * slo:api_latency:ratio_rate30m

  # --------------------------------------------------------------------------
  # Database Uptime 99.99% (probe success)
  # --------------------------------------------------------------------------
  - name: slo-db-uptime
    rules:
      - record: slo:db_uptime:ratio_rate5m
        expr: |
          avg(rate(pg_up{service="postgres"}[5m]))
      - record: slo:db_uptime:ratio_rate30m
        expr: |
          avg(rate(pg_up{service="postgres"}[30m]))
      - record: slo:db_uptime:error_burn_rate_1h
        expr: |
          (1 - 0.9999) * (1 - slo:db_uptime:ratio_rate5m)
      - record: slo:db_uptime:error_burn_rate_6h
        expr: |
          (1 - 0.9999) * (1 - slo:db_uptime:ratio_rate30m)

  # --------------------------------------------------------------------------
  # Backup Freshness — a successful backup within the last 24h
  # --------------------------------------------------------------------------
  - name: slo-backup-freshness
    rules:
      - record: slo:backup_freshness:ok
        expr: |
          clamp_max(time() - max(deepa_bms_last_backup_timestamp), 86400) <= 86400
      - record: slo:backup_freshness:error_burn_rate_1h
        expr: |
          (1 - 1.0) * (1 - slo:backup_freshness:ok)
      - record: slo:backup_freshness:error_burn_rate_6h
        expr: |
          (1 - 1.0) * (1 - slo:backup_freshness:ok)

  # --------------------------------------------------------------------------
  # Burn-Rate Alerts (fast + slow windows, 14.4x and 6x thresholds)
  # --------------------------------------------------------------------------
  - name: slo-burn-rate-alerts
    rules:
      - alert: APIAvailabilityBurnRateFast
        expr: |
          slo:api_availability:error_burn_rate_1h > (14.4 * (1 - 0.999))
        for: 2m
        labels:
          severity: critical
          slo: api-availability
        annotations:
          summary: "API availability SLO burn rate critical (fast window)"
          description: "API availability is burning error budget ~14x faster than sustainable (99.9% SLO)."

      - alert: APIAvailabilityBurnRateSlow
        expr: |
          slo:api_availability:error_burn_rate_6h > (6 * (1 - 0.999))
        for: 15m
        labels:
          severity: warning
          slo: api-availability
        annotations:
          summary: "API availability SLO burn rate elevated (slow window)"
          description: "API availability error budget consumption is ~6x above target over 6h."

      - alert: APILatencyBurnRateFast
        expr: |
          slo:api_latency:error_burn_rate_1h > (14.4 * (1 - 0.99))
        for: 2m
        labels:
          severity: critical
          slo: api-latency
        annotations:
          summary: "API latency SLO burn rate critical (fast window)"
          description: "Requests slower than 1s are burning budget ~14x faster than sustainable (99% SLO)."

      - alert: APILatencyBurnRateSlow
        expr: |
          slo:api_latency:error_burn_rate_6h > (6 * (1 - 0.99))
        for: 15m
        labels:
          severity: warning
          slo: api-latency
        annotations:
          summary: "API latency SLO burn rate elevated (slow window)"
          description: "Latency budget consumption is ~6x above target over 6h."

      - alert: DBUptimeBurnRateFast
        expr: |
          slo:db_uptime:error_burn_rate_1h > (14.4 * (1 - 0.9999))
        for: 2m
        labels:
          severity: critical
          slo: db-uptime
        annotations:
          summary: "Database uptime SLO burn rate critical (fast window)"
          description: "Database downtime is burning budget ~14x faster than sustainable (99.99% SLO)."

      - alert: BackupFreshnessBreach
        expr: |
          slo:backup_freshness:ok == 0
        for: 10m
        labels:
          severity: critical
          slo: backup-freshness
        annotations:
          summary: "Backup freshness SLO breached"
          description: "No successful backup recorded within the 24h window (99.99% uptime / freshness SLO)."
YAML

echo "Generated SLO recording rules + burn-rate alerts at: $OUT_FILE"
